### ISSUE TITLE
Celestial bodies pop-up does not work on mobile.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/helioviewer.org#391]
I checked this for the recent Venus and Mercury observations in LASCO C3. Clicking on the name "Venus" and "Mercury" did not bring the pop-up. In addition, the Parker Solar Probe pop-up did not work.

**Comment by btaylor-sesda** [comment]
@wafels The pop-ups for the planetary bodies, should be working now. I'll try to get the PSP ones to work.

**Comment by wafels** [comment]
Still doesn't work for me :-(

**Comment by btaylor-sesda** [comment]
@wafels In Browserstack, the pop-up showed for me when I selected iPhone XR. 
I zoomed out, moved to the far left of the photo and clicked on the Mercury label. 

![image](https://user-images.githubusercontent.com/87322123/202536230-28cbc6e7-8ccd-44d4-b99c-ee904a9fbab5.png)

**Comment by wafels** [comment]
Still doesn't work for me on my phone. Maybe I am not hitting the target?

**Comment by btaylor-sesda** [comment]
@wafels It's very possible, perhaps it would be easier to enlarge the font of the labels on mobile if that's the case. 
I'll try that and see if it helps.
